title: Site
columns:
  - width: 1/2
    sections:
      fields:
        type: fields
        fields:
          footer:
            type: textarea
  - width: 1/2
    sections:
      pages:
        type: pages